apiVersion: v1
kind: Service
metadata:
  namespace: camel-wfp
  name: camel-wfp-integration
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: camel-wfp-app-sandbox-integration
