apiVersion: v1
kind: Service
metadata:
  namespace: camel-freedomhouse
  name: camel-freedomhouse
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app: camel-freedomhouse-app-sandbox
