apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/camel-time-app/
  - ../base/camel-wfp-app-ui/
  - ../base/camel-wfp-app-integration/
  - ../base/paasport-admin-dashboard-integration.yaml
  - ../base/paasport-admin-dashboard-ui.yaml
patches:
