apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: cluster-tools
spec:
  values:
    vpcId: vpc-0c3c73976ec606bdc
    clusterName: sandbox-cluster
    region: us-east-1
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::744692937981:role/aws-load-balancer-controller-sandbox"

