apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: cluster-tools
spec:
  values:
    clusterName: bitbrew-eks-infra-dev-cluster
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::744692937981:role/irsa-aws-load-balancer-controller-sandbox"

