apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-resource-report
  namespace: cluster-tools
spec:
  rules:
    - host: "kube-resource-report.sandbox.paasport.io"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kube-resource-report
              port:
                number: 80

