apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: cluster-tools
spec:
  interval: 1m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: '1.2.7'
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: cluster-tools
      interval: 1m
  values:
    podLabels:
      eks.amazonaws.com/fargate-profile: cluster-tools-profile
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 300Mi
