apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: cluster-tools
spec:
  interval: 1m
  chart:
    spec:
      chart: external-dns
      version: '1.2.0'
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: kube-system
      interval: 1m
  values:
    podLabels:
      eks.amazonaws.com/fargate-profile: cluster-tools-profile
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 300Mi
