apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: cluster-tools
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/external-dns/
