apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubernetes-external-secrets
  namespace: cluster-tools
spec:
  interval: 1m
  url: https://external-secrets.github.io/kubernetes-external-secrets/
